logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /var/log/webapp/requests.log
      record_log_file_path: true
  processors:
    my-app-processor:
      type: parse_json
      time_key: jsonPayload.time
      time_format: "%Y-%m-%dT%H:%M:%S.%L%Z"
    extract_severity:
      type: extract_fields
      fields:
      level:
        regex: level="(?<level>\w+)"
  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors: [my-app-processor,move_severity