name: Packer CI

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Debug info
        run: |
          ls -al
          
      - name: init
        run: |
          echo "Running packer init..."
          packer init
          echo "Packer init completed."

      - name: fmt
        run: |
          echo "Running packer fmt..."
          packer fmt
          echo "Packer fmt completed."

      - name: validate
        run: |
          echo "Running packer validate..."
          packer validate 
          echo "Packer validate completed."
