name: Packer CI

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Run packer init
        id: init
        run: "packer init ."

      - name: Run packer format
        id: fmt
        run: "packer fmt -check ."

      - name: Run packer validate
        id: validate
        run: "packer validate ."

      - name: Run `packer build`
        id: build
        run: "packer build ."
