name: Packer CI

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: init Packer
        run: packer init .
        
      - name: Format Packer
        run: packer fmt .

      - name: Validate Packer
        run: |
          packer validate .
          packer build .
