name: Workflow CI
 
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: test-checker
    runs-on: ubuntu-latest
 
    steps:
      - name: Create webapp.zip
        run: |
            zip -r webapp.zip .
            
      - name: Install Packer
        run: |
          curl -fsSL https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip -o packer.zip
          unzip packer.zip -d /tmp
          sudo mv /tmp/packer /usr/bin/packer
          packer --version

      - name: Initialize Packer
        run: packer init main.pkr.hcl

      - name: Format Packer template
        run: packer fmt main.pkr.hcl

      - name: Validate Packer template
        run: packer validate -var 'project_id=${{ secrets.GOOGLE_CONFIG }}' main.pkr.hcl
