name: Github action

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up MySQL
      run: |
        sudo apt-get update
        sudo apt-get install mysql-server -y
        sudo service mysql start
        sudo mysql -e "CREATE DATABASE Cloud;"
        sudo mysql -e "CREATE USER 'Cloud'@'localhost' IDENTIFIED BY 'Cloud123';"
        sudo mysql -e "GRANT ALL PRIVILEGES ON Cloud.* TO 'Cloud'@'localhost';"
        sudo mysql -e "FLUSH PRIVILEGES;"
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run Flask Application
      run: |
        export DB_USER=Cloud
        export DB_PASSWORD=Cloud123
        export DB_NAME=Cloud
        python main.py &
      
    - name: Wait and Run Integration Test
      run: |
        sleep 15
        python tests/integration.py
