name: Github action

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: Cloud123
          MYSQL_DATABASE: Cloud
          MYSQL_USER: Cloud
          MYSQL_PASSWORD: Cloud123
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run MySQL Initialization Script
      run: |
        echo "Waiting for MySQL to start"
        sleep 30
        mysql -h 127.0.0.1 -P 3306 -u Cloud -pCloud123 Cloud

    - name: Run Flask Application
      run: |
        export DB_USER=Cloud
        export DB_PASSWORD=Cloud123
        export DB_NAME=Cloud
        python main.py &
      
    - name: Wait and Run Integration Test
      run: |
        sleep 15
        python tests/integration.py
