name: Github action

on:
  pull_request:

env:
  HOST: ${{ secrets.HOST }}
  DB_USER: cloud
  DB_PASSWORD: Cloud123
  DB_NAME: cloud

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure MySQL
      run: |
       sudo service mysql start
       sudo mysql -u root -p"root" -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_NAME }};"
       sudo mysql -u root -p"root" -e "CREATE USER IF NOT EXISTS '${{ secrets.DB_USER }}'@'localhost' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}';"
       sudo mysql -u root -p"root" -e "GRANT ALL PRIVILEGES ON ${{ secrets.DB_NAME }}.* TO '${{ secrets.DB_USER }}'@'localhost';"
       sudo mysql -u root -p"root" -e "FLUSH PRIVILEGES;"
       
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run Flask Application
      run: |
        export DB_USER=${{ secrets.DB_USER }}
        export DB_PASSWORD=${{ secrets.DB_USER_PASSWORD }}
        export DB_NAME=${{ secrets.DB_NAME }}
        python main.py &
      
    - name: Wait and Run Integration Test
      run: |
        sleep 15
        python tests/integration.py
