name: Github action

on:
  pull_request:

env:
  HOST: localhost
  MYSQL_ROOT_PASSWORD : root
  DB_USER: cloud
  DB_PASSWORD: Cloud123
  DB_NAME: cloud

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure MySQL
      run: |
        sudo service mysql start
        sudo mysql -u root -p"${MYSQL_ROOT_PASSWORD}" -e "CREATE DATABASE IF NOT EXISTS cloud;"
        sudo mysql -u root -p"${MYSQL_ROOT_PASSWORD}" -e "CREATE USER IF NOT EXISTS cloud@'localhost' IDENTIFIED BY 'Cloud123';"
        sudo mysql -u root -p"${MYSQL_ROOT_PASSWORD}" -e "GRANT ALL PRIVILEGES ON cloud.* TO cloud@'localhost';"
        sudo mysql -u root -p"${MYSQL_ROOT_PASSWORD}" -e "FLUSH PRIVILEGES;"
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run Flask Application
      run: |
        export DB_USER=${{ secrets.DB_USER }}
        export DB_PASSWORD=${{ secrets.DB_USER_PASSWORD }}
        export DB_NAME=${{ secrets.DB_NAME }}
        python main.py &
      
    - name: Wait and Run Integration Test
      run: |
        sleep 15
        python tests/integration.py
